const backgroundImgs = {
    EU: {
        ad: require('..//assets/countries_background/eu/ad.png'),
        al: require('..//assets/countries_background/eu/al.png'),
        at: require('..//assets/countries_background/eu/at.png'),
        ba: require('..//assets/countries_background/eu/ba.png'),
        be: require('..//assets/countries_background/eu/be.png'),
        bg: require('..//assets/countries_background/eu/bg.png'),
        by: require('..//assets/countries_background/eu/by.png'),
        ch: require('..//assets/countries_background/eu/ch.png'),
        cz: require('..//assets/countries_background/eu/cz.png'),
        cy: require('..//assets/countries_background/eu/cy.png'),
        de: require('..//assets/countries_background/eu/de.png'),
        dk: require('..//assets/countries_background/eu/dk.png'),
        ee: require('..//assets/countries_background/eu/ee.png'),
        es: require('..//assets/countries_background/eu/es.png'),
        fi: require('..//assets/countries_background/eu/fi.png'),
        fo: require('..//assets/countries_background/eu/fo.png'),
        fr: require('..//assets/countries_background/eu/fr.png'),
        hr: require('..//assets/countries_background/eu/hr.png'),
        hu: require('..//assets/countries_background/eu/hu.png'),
        gb: require('..//assets/countries_background/eu/gb.png'),
        gr: require('..//assets/countries_background/eu/gr.png'),
        ie: require('..//assets/countries_background/eu/ie.png'),
        is: require('..//assets/countries_background/eu/is.png'),
        it: require('..//assets/countries_background/eu/it.png'),
        li: require('..//assets/countries_background/eu/li.png'),
        lt: require('..//assets/countries_background/eu/lt.png'),
        lu: require('..//assets/countries_background/eu/lu.png'),
        lv: require('..//assets/countries_background/eu/lv.png'),
        md: require('..//assets/countries_background/eu/md.png'),
        me: require('..//assets/countries_background/eu/me.png'),
        mk: require('..//assets/countries_background/eu/mk.png'),
        mt: require('..//assets/countries_background/eu/mt.png'),
        nl: require('..//assets/countries_background/eu/nl.png'),
        no: require('..//assets/countries_background/eu/no.png'),
        pl: require('..//assets/countries_background/eu/pl.png'),
        pt: require('..//assets/countries_background/eu/pt.png'),
        ro: require('..//assets/countries_background/eu/ro.png'),
        va: require('..//assets/countries_background/eu/va.png'),
        si: require('..//assets/countries_background/eu/si.png'),
        se: require('..//assets/countries_background/eu/se.png'),
        sk: require('..//assets/countries_background/eu/sk.png'),
        ua: require('..//assets/countries_background/eu/ua.png')
    },

    NA: {
        us: require('..//assets/countries_background/na/us.png'),
        ca: require('..//assets/countries_background/na/ca.png'),
        mx: require('..//assets/countries_background/na/mx.png')
    },

    SA: {
        aw: require('..//assets/countries_background/sa/aw.png'),
        ar: require('..//assets/countries_background/sa/ar.png'),
        bo: require('..//assets/countries_background/sa/bo.png'),
        br: require('..//assets/countries_background/sa/br.png'),
        cl: require('..//assets/countries_background/sa/cl.png'),
        pe: require('..//assets/countries_background/sa/pe.png'),
        co: require('..//assets/countries_background/sa/co.png'),
        cw: require('..//assets/countries_background/sa/cw.png'),
        ec: require('..//assets/countries_background/sa/ec.png'),
        fk: require('..//assets/countries_background/sa/fk.png'),
        gd: require('..//assets/countries_background/sa/gd.png'),
        gy: require('..//assets/countries_background/sa/gy.png'),
        py: require('..//assets/countries_background/sa/py.png'),
        sr: require('..//assets/countries_background/sa/sr.png'),
        tt: require('..//assets/countries_background/sa/tt.png'),
        uy: require('..//assets/countries_background/sa/uy.png'),
        ve: require('..//assets/countries_background/sa/ve.png'),
        gf: require('..//assets/countries_background/sa/gf.png')
    },

    OC: {
        au: require('..//assets/countries_background/oc/au.png'),
        fj: require('..//assets/countries_background/oc/fj.png'),
        nc: require('..//assets/countries_background/oc/nc.png'),
        nz: require('..//assets/countries_background/oc/nz.png'),
        pg: require('..//assets/countries_background/oc/pg.png'),
        sb: require('..//assets/countries_background/oc/sb.png'),
        vu: require('..//assets/countries_background/oc/vu.png')
    },

    AS: {
        af: require('..//assets/countries_background/as/af.png'),
        ae: require('..//assets/countries_background/as/ae.png'),
        am: require('..//assets/countries_background/as/am.png'),
        az: require('..//assets/countries_background/as/az.png'),
        bd: require('..//assets/countries_background/as/bd.png'),
        bn: require('..//assets/countries_background/as/bn.png'),
        bt: require('..//assets/countries_background/as/bt.png'),
        id: require('..//assets/countries_background/as/id.png'),
        in: require('..//assets/countries_background/as/in.png'),
        ir: require('..//assets/countries_background/as/ir.png'),
        iq: require('..//assets/countries_background/as/iq.png'),
        il: require('..//assets/countries_background/as/il.png'),
        jo: require('..//assets/countries_background/as/jo.png'),
        kz: require('..//assets/countries_background/as/kz.png'),
        kg: require('..//assets/countries_background/as/kg.png'),
        kh: require('..//assets/countries_background/as/kh.png'),
        kr: require('..//assets/countries_background/as/kr.png'),
        kw: require('..//assets/countries_background/as/kw.png'),
        la: require('..//assets/countries_background/as/la.png'),
        lb: require('..//assets/countries_background/as/lb.png'),
        lk: require('..//assets/countries_background/as/lk.png'),
        mm: require('..//assets/countries_background/as/mm.png'),
        mn: require('..//assets/countries_background/as/mn.png'),
        mv: require('..//assets/countries_background/as/mv.png'),
        jp: require('..//assets/countries_background/as/jp.png'),
        ru: require('..//assets/countries_background/as/ru.png'),
        cn: require('..//assets/countries_background/as/cn.png')
    },

    AF:  {
        eg: require('..//assets/countries_background/af/eg.png'),
        ao: require('..//assets/countries_background/af/ao.png'),
        mg: require('..//assets/countries_background/af/mg.png')
    }
}

export { backgroundImgs }; 